### ISSUE TITLE
capacity overflow rusty-blockparser-0.11.0

### ISSUE THREAD

**Issue by Githrasher** [gcarq/rusty-blockparser#97] opened 2023-07-11 05:38 UTC
![Err](https://github.com/gcarq/rusty-blockparser/assets/139203418/d7ac0040-7aed-4f26-804b-bf858a314ea3)
I built the latest version 0.11.0 .
And I get this error "capacity overflow"
Could you help me fix this.

**Comment by gcarq** [comment] 2023-07-11 08:16
Can you pass `-v` to increase verbosity to get the debug logs? Also which system specification do you have? `capacity overflow` normally hints to an out of memory situation

**Comment by gcarq** [comment] 2023-07-11 09:28
16GB of RAM should be fine at this point. I'm not to sure how Windows works in this regard, but can it be that C:\Temp is mapped into RAM (similar to tempfs on linux) and the RAM will fill up very quickly because the program is started in C:\Temp and also the dump path is also set to this.

Can you try to execute this somewhere else like C:\Users\... (also setting a different dump path) and monitor the memory usage when starting it?

Also make sure to build the executable with `cargo build --release`.

**Comment by Githrasher** [comment] 2023-07-11 09:47
> На данный момент 16 ГБ оперативной памяти должно хватить. Я не уверен, как работает Windows в этом отношении, но может ли быть так, что C:\Temp отображается в ОЗУ (аналогично tempfs в Linux), и ОЗУ будет заполняться очень быстро, потому что программа запускается в C:\ Temp, а также путь дампа также установлены на это.
> 
> Можете ли вы попробовать выполнить это где-нибудь еще, например, C:\Users... (также задав другой путь дампа) и контролировать использование памяти при его запуске?
> 
> Также не забудьте собрать исполняемый файл с расширением `cargo build --release`.

![err3](https://github.com/gcarq/rusty-blockparser/assets/139203418/b061f0de-4976-4414-bb97-11700c893e65)

**Comment by Githrasher** [comment] 2023-07-11 09:51
![err3](https://github.com/gcarq/rusty-blockparser/assets/139203418/e38812e7-80d6-4f7f-9044-744aa988c2e0)

So I built the project cargo build --release

**Comment by gcarq** [comment] 2023-07-11 10:23
> Could you give already built rusty-blockparser

I think the binary works fine, however I cannot reproduce this on linux and have currently no windows instance to test on.
Please check and verify the RAM usage with the task manager or similar things to rule out OOM errors.

It might also be worth to test another command like `simplestats` which doesn't allocate a lot of memory upfront or versions 0.9.0 and 0.10.0  to narrow it down a bit.

**Comment by Githrasher** [comment] 2023-07-11 10:39
> > Could you give already built rusty-blockparser
> 
> I think the binary works fine, however I cannot reproduce this on linux and have currently no windows instance to test on. Please check and verify the RAM usage with the task manager or similar things to rule out OOM errors.
> 
> It might also be worth to test another command like `simplestats` which doesn't allocate a lot of memory upfront or versions 0.9.0 and 0.10.0 to narrow it down a bit.

![err4](https://github.com/gcarq/rusty-blockparser/assets/139203418/ef3c127a-32c2-4a33-800b-ff5faa0dc137)
I tried it on a 32GB PC too.

**Comment by Githrasher** [comment] 2023-07-12 04:12
![err5](https://github.com/gcarq/rusty-blockparser/assets/139203418/54047c8e-e1b0-4907-9a3e-27481b8e8349)
Hello.
I tried this today in VirtualBox Ubuntu 18

**Comment by gcarq** [comment] 2023-07-12 08:13
This stacktrace is very helpful and brings us closer to the solution. It seems most likely that the blockchain data is corrupt, can you resync (or verify/repair it in any way)?.

The problem is that the parser tries to read some[ variable length integer](https://en.bitcoin.it/wiki/Protocol_documentation#Variable_length_integer) in `read_tx` that have a special encoding, if this data is corrupt the parser tries to allocate an unreasonable amount of memory and bails out, which is most likely the case here.

**Comment by gcarq** [comment] 2023-07-18 10:58
Any update on this one? Did it work after resyncing the chain?

**Comment by gcarq** [comment] 2023-07-20 09:58
Closing this, feel free to reopen if a resync doesn't help

**Closed by gcarq** 2023-07-20 09:58 UTC
Labels: bug
