### ISSUE TITLE
statment incomplete in result file

### ISSUE THREAD

**Issue by hamnaz** [gcarq/rusty-blockparser#50] opened 2019-01-28 23:05 UTC
txid;indexOut;height;value;address
16162f8e21f6b184f60d793f091aec7773e5f6146b56061655304015e2350d2;;558965;1000000;3GbJNPBSWTjq4db6wUZNFyMBfnLYk7fNzj
92351f0ce2c65033efb8d1ad326296f2a2cefa726e3a17db7f23e98d4074237;;559900;0;
68ad83587fb2bb690630d5dcbd205c969f0fa7e737019b61844cc362ebc7ee6;6;559040;5100000;1APeB4CbJEbPit6zCfyPr7b5zRncQKys77
efbaaf612d142f2508749d0a16429ebd478ea4c778697a2e8510a4a78c45596;;559605;13571995;3CQuasFfeEzz38WjH384SrupExYrgoXRug
3d4e325e3782b02d3af0a381cc6b8ee69af51feabf084b3010bce57f7de11c3;;560495;1592228;3DNkb3dXJMwTkuGDPMmpJg47eZ8m5ZSLem
5a734f115f1a6432aa7b177753e956aa20fa526944fd387bfe25b7ee404741a;;559264;0;
9a915e478208ec050744e18b800671488120365b7cf5a17a3096b063f0d36a6;;559843;9980741;3LkoRFpzM6xDMkHXUCVM9wVNw5Kmp1Cj6o
51d6ce31abd4012cfea3b67c80e575915fb07250b2518c6ec924511f0920382;;560132;0;
7255cdc2b0ca39af54d2473197446746557095cd423ab27ed55038e250cfa34;;560183;917877;12hp65EJtxriF69tR6yZDZqQP7jYTNzKNw
f22ce9d611e1e986ccdde36b8232bc25ad1a2b03e13e4e4771a9bbfc64c42af;;559034;95641;37NSajsYqfVvJMrLetw9C8VmNF5WPg3uFn
80a22bb9bf548c629ca6aa92a95a4281e41367c18c4aca7307a43bfcce77c89;;559306;342639;14Ap88Hfa9Py3Wp8qxxdockr9MCqw9rHsZ
e7c428655be162a6aea7592379ff9b00f2d21e6061330f713f8c70b8c220d38;15;560032;400882;17WvxWpbHCw76DFUrrrWYSpv8MupfYAZim
01465f9c2d4369e77b623e379b28b0cba40a71302ed8b69bd7ba3320871db6c;;560349;546;1DURUZXNM7k3fboaHhoPfTDPSYhw4tZQqQ
b0381303b22b9e73cb07bc9e6dd6c8af7cdb25ffa00cc11a89c460eb2e8074e;;559015;28000000;33DJ3vYkrVjYV7BddiZuoivDKw68UqygfE
7db27874a01bfbd056961693439ec9c9ce18137423ea0e15040857169e65f2c;;559372;0;
2cb0ad30b6e15331e8896e467e25ab6212ab4d4fa73a5469dfbaba0e7ad2c43;;560051;1300000;1N3DrFuem5VXHwRRyn17MYhfQgZJy1RfaX
dd34e2b8695657143a24f793f04c36e46b2787ef30a5623f61ec46458885656;2;560126;89569;3F1XMfL8LCQy397c9e4Z7ypbR6xnf48fjm
a089d11f62f7ef6dcbe2c0d8726b84c04c5c7854f26c51132f5ab3c851f9454;;559047;0;
7b693cc57fdac4fc512550bb6665fff821f5e18ac49be3db3815af2117de4af;;559397;37304671;1KcMRh8Jc12LjVC9eF3B1Yj2CHGNen5RBX
c9e13d5f86bc148958cefed5ba2861eba3a8f670cf8ca21ded039e9c5a00e3c;;559138;0;
7bcac9224c630b5c5319119c4cd7f2516b27a670df4c126e3e47b2f4c7e9942;;560128;0;
3912314e4f73327acb9a695f01c94494b42c089bcb58b37dde39ba612e388e0;;559114;10171;15MoKovANartYEGqz63bSqGfRbN87JQunh
99eda53f385f74f03c4612c069de50d62dc194c0b529f42a1587e06a172015e;;559723;0;
0c84ec205fe2515a7c6223ffd1639c72d3c97deda2756f4152c52537ddfef1b;;560511;3285269;3FQmtqhYP4FKpPnGPxjwoHJRCpSjbFpsoL
374f7dc5625c21fcf51f777f836eabeb9422212ec01b7c551aca1d12578eed2;;560510;0;
e8abfd226eb4a8c2ffe74715625419f7bcec23cdd9dbbf990338bd14de44ec3;;558983;0;
ed821acb385a732a0e008b0e53d8498380ae66070d2ad46773886b287b7dfae;;559558;0;
032cea70786a9a019ba101f46f73bc4ce19cbb6427c7be26a82b86079edb60f;;559433;0;
662f483f638cfe0f2f62e84540ae66736131d20090446b93d6698002d36d5e6;;559726;13833669;1n2KRyDfMW1k72Bsqwxqgb6bXy9S14KK7
4fc464283407d533c401d94e488b8b2f2375830e26aaa7bde40ad5c8af60854;;560453;0;

see above its txid last 64 char missing in complete file
and parser status

[03:37:22] INFO - dispatch: Status:   1310 Blocks processed. (left:    323, avg:    13 blocks/sec)
[03:37:31] INFO - dispatch: All threads finished.
[03:37:31] INFO - dispatch: Done. Processed 1633 blocks in 1.82 minutes. (avg:    14 blocks/sec)
[03:37:33] INFO - callback: Done.
Dumped all 560539 blocks:
        -> transactions:   3387477
        -> inputs:         6918230
        -> outputs:        8220615
[03:37:33] INFO - dispatch: Saving block headers as chain.json ...
[03:37:35] INFO - main: Fin.

actuall file contain 2487357 txid and same total lines are 2487357
whats wrong with this parser ??????

**Comment by gcarq** [comment] 2019-01-29 16:48
I'm sorry but the source code hasn't been updated since a few years, so it doesn't understand newer script opcodes and I'm sure there are bugs. If you want the issues fixed, feel free to open a pull request.

**Comment by hamnaz** [comment] 2019-01-29 21:15
kindly update here 
https://crates.io/crates/rusty-blockparser
Versions

0.6.1 Oct 19, 2017
0.6.0 Oct 26, 2016
0.5.4 Oct 12, 2016
0.5.3 Sep 6, 2016
0.5.0 Jul 15, 2016

last updated May 3, 2018 not at crates.io, if you update crates.io with May 3, 2018 version, maybe basic 64 char txid we can see
thankx

**Comment by hamnaz** [comment] 2019-01-31 19:43
source comming from crates.io is old of 19 oct 2017, its come in cargo registry, pls update it at crates.io
2nd i change some system settings, its compile but no output file at crago bin
![1](https://user-images.githubusercontent.com/42878992/52080770-66c76880-25ba-11e9-80b1-e7ecd460db6a.jpg)

**Comment by hamnaz** [comment] 2019-01-31 21:44
successfully compile, and getting 64 count in txid
but result need to be understand as total counting txid
![2](https://user-images.githubusercontent.com/42878992/52087416-363bfa80-25cb-11e9-8f29-6f39b8610eb3.jpg)

**Comment by gcarq** [comment] 2020-07-18 04:06
Should be fixed with the latest version. For unrecognised or invalid txs the address is ommitted, this is not a bug. However the latest commit on the master branch doesn't include unrecognized txs in the unspentcsvdump

**Closed by gcarq** 2020-07-18 04:06 UTC
